[package]
name = "steganopng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
optional-field = "0.1.4"
rand = "0.8.5"
deoxys = "0.1.0"
hex = "0.4.3"
generic-array = "0.14.7"
